### ISSUE TITLE
Add license field

### ISSUE THREAD

**Issue by hadley** [rstudio/pins-r#569]
A string

**Comment by juliasilge** [comment]
@hadley Can you give any more detail on what you were thinking about here? Like a license field in the pin metadata so folks can specify the license of the data in their pin?

**Comment by hadley** [comment]
Yes? If that doesn't sound like it's something important feel free to close.

**Comment by juliasilge** [comment]
Most folks use pins in an internal context where a license isn't that relevant. Let's close for now and reconsider this based on user feedback.
