### ISSUE TITLE
Implement modern google cloud storage board

### ISSUE THREAD

**Issue by hadley** [rstudio/pins-r#572]
Please 👍 this issue if you'd like this implemented.

**Comment by GitHunter0** [comment]
It would be really nice as well to get the Github board working again

**Comment by hadley** [comment]
@GitHunter0 (a) it's already fixed in the dev version and (b) it's not useful to comment on an unrelated issue

**Comment by MarkEdmondson1234** [comment]
I could help with this to help along the vetiver integration.  I guess implementing GCS versions of the AWS functions here?
https://github.com/rstudio/pins/blob/main/R/board_s3.R  - I have just done this with targets so imagine could copy across several of those functions - available for review in this pull request https://github.com/ropensci/targets/pull/722

**Comment by hadley** [comment]
@MarkEdmondson1234 that'd be great! Both `board_s3()` and `board_azure()` are good places to look at first, and there are some suggestions on implementation order in #481.

**Comment by MarkEdmondson1234** [comment]
Great, have made a start and will see how it goes.

**Comment by smach** [comment]
pins for Python has made Google Cloud a more compelling feature, since I could now use pins to collaborate with Python-using colleagues

**Comment by MarkEdmondson1234** [comment]
It's still on my todo but just finishing my book, this is the next project. But if someone can pick it up before August go for it.

**Comment by smach** [comment]
@MarkEdmondson1234  Understood. Just popped by here because the recent RStudio getting started with pins video said to upvote the issue if we were interested.

**Comment by juliasilge** [comment]
@MarkEdmondson1234 are you still interested in working on this, or should one of us pick it up? No pressure either way!

**Comment by MarkEdmondson1234** [comment]
Hi @juliasilge , it was vetiver that motivated me to start looking at this, but I've in the meantime I have started a new job that is going to take some time to onboard R modelling so I can justify some code time, so if you have time now to work on it please go ahead. I can at least reply to any comments/questions around Cloud Storage if needed. There are also aspects of the Vertex AI platform I think would be very beneficial when I get the hours.

**Comment by juliasilge** [comment]
This is now in the development version of pins, so we would be super happy for you to try it out and give any feedback on using pins with GCS! You can install via `remotes::install_github("rstudio/pins-r")`.

**Comment by MarkEdmondson1234** [comment]
Woohoo thanks!
