### ISSUE TITLE
Feature Request: Re-enabling data versioning by hash only

### ISSUE THREAD

**Issue by afshinmhCLG** [rstudio/pins-r#589]
**Desired behavior:**  
Data version changes when data changes. For example, repeated execution of `pin_write(x, board = myboard, version = T)`  does not generate different data versions as long as x is the same.

**Current behavior:**  
Data is re-written under a  new version each time `pin_write` is executed even when content, name, description, title, etc. are all the same! 

I realize hash of the data is stored so one can identify duplicates, but avoiding data duplication in the first place was at the core of the value `pins` offered teams. 

**Feature request:** 
Given that the time stamp was added to the version signature in version 1.0.1, I am sure it has a use-case, but would it be possible to enable an option where the signature is the hash of the data or even better a hash encompassing data, and other user defined metadata (e.g. description and other tags)?

**Comment by robertsehlke** [comment]
+1

I'm just testing out pins, which so far has been very slick with s3 backend, and went looking in the issues if someone else had already asked about this.

For my use case, even just an optional duplicate detection built into `pin_write()` would serve the purpose. I.e. if the user chooses: calculate the hash, query existing versions, and only create a new version if it is not a duplicate.

This would be a simple QoL option that does not affect current structures.

**Comment by machow** [comment]
It seems like the big challenge here for pins is that version name is made of two parts (`"{timestamp}-{hash}"`), and has two jobs:

* timestamp: allow for quick sorting of pin versions (e.g. to get the latest pin)
* hash: allow for quick checking whether contents are identical

It seems like versioning by hash only would require a new strategy for tracking timestamp info. For example, on `pin_write()` we check for a duplicate, and instead a filesystem `mv` to rename the duplicate version to the updated timestamp.

E.g. 

* a write of data with the hash `abc` on `2022-02-02`
* verifies a previous version has a matching hash `abc`
* moves `{old_timestamp}-abc` to `{new_timestamp}-abc`.

It seems like it might require fairly substantial changes, though....!

**Comment by robertsehlke** [comment]
Agreed - a simpler way could be to let the user choose not to upload/update at all if there already is a version with the same hash (also keeps external references stable).

**Comment by iainmwallace** [comment]
Agreed, this capability would be very useful.

perhaps there could be a helper function such as pin_unique_write that only writes if the dataset is unique.

**Comment by machow** [comment]
Thanks for all the confirmation that this would be useful, and added context! I haven't seen the original pins in action, so it's helpful to hear that this feels like an original feature that got taken out.

> it shouldn't be a big undertaking to track additional metadata properly rather than getting the version to do double duty

It seems like a key here is pins is using `{timestamp}-{hash}` not just as metadata (which is already recorded in the `data.txt` file), but essentially as a partition (e.g. you can `ls` timestamp and hash info, without having to open a file, maybe loosely similar to how [hive partitions work](https://sparkbyexamples.com/apache-hive/hive-partitions-explained-with-examples/)). 

A `pins_write_unique()` function seems much easier to implement. What do y'all picture `pin_unique_write()` doing if it hits a duplicate? Throwing an error? (or just printing a message?)

**Comment by hadley** [comment]
Just a note that this:

> keeps a separate object (a board level pin actually) that tracks metadata above (and more) and gets updated with each equivalent of pin_write. 

might work for your use case but is very dangerous in if more than one person might be writing to the board because you'll run the risk of race conditions leading to the metadata store not matching what's actually recorded on disk. This was a major flaw with the design of pins v1 that had to be fixed for v2.

**Comment by robertsehlke** [comment]
> A pins_write_unique() function seems much easier to implement. What do y'all picture pin_unique_write() doing if it hits a duplicate? Throwing an error? (or just printing a message?)

Just printing a message/warning would already be great imo.

Ideal case would be a return value that contains all metadata fields of the exact written or unwritten-because-duplicated version ( `pin_meta` outputs for that version), but that would be a deeper change if you want consistency across the regular `pin_write` as well. Either way, likely best to leave existing metadata untouched (as @hadley noted).

PS: even just exposing the hash calculation as stand-alone function would make writing a wrapper for this trivial, given other utility functions. Maybe that's easy, haven't had the time to dive very deep yet.

**Comment by amashadihossein** [comment]
> might work for your use case but is very dangerous in if more than one person might be writing to the board because you'll run the risk of race conditions

Thanks, valid point and what's dangerous and what's worth mitigation effort relates to use case/specifics and preferences. Regardless, it seems pins is ok with rewrite of the same content over and over again and offers to keep track of the writes which is useful.

**Comment by hadley** [comment]
@robertsehlke I don't think just exposing the hash calculation is sufficient; we'd need some consideration of the length of the hash. IIRC it's currently truncated because the timestamp provides most of the identity; if you're relying on the hash alone you'd need to ensure that the chance of spurious collisions is very low.

**Comment by robertsehlke** [comment]
True, and timestamps + shortened hash are generally a nice compromise for human readability.

Does `pin_versions` parse the folder name or use the `data.txt` files? If it returned the full hash that would solve the issue, no need to change folder/version naming.

**Comment by kmasiello** [comment]
Adding some color to the issue.  Pinning every version, even if the data is unchanged, is painful in two ways:
1. A daily scheduled job on Connect that writes a pin will result in a pin with a very long list of versions, even if in reality, the data did change. This obscures the visibility of when the data actually changes. Users expect that they can pull up a version history of the pin and quickly see the handful of times the data actually changed.  
2. repeated writes of the same data on the Connect server can consume resources. In practice, it's not always a practical or quick fix to just increase storage. The data scientists likely don't have visibility of the fact that their pin writes/rewrites are consuming a lot of storage space. And server admins may not be familiar enough with the data science workflows to appreciate that pin versions are a culprit in why server space is being consumed.

**Comment by hadley** [comment]
As far as I can tell, this was never documented behaviour with old versions by pins, and I suspect it was just an implementation detail that folks took advantage of. This isn't to say that we shouldn't make it possible, just to note that we need to carefully design it from the ground up.

**Comment by amashadihossein** [comment]
> 2\. repeated writes of the same data on the Connect server can consume resources

In my experience, this is very much a real concern. I have witnessed multiple times connect filling up leading to folks scrambling to allocate more resources (and actual downtime). Of course, connect filling up is not totally eliminated by avoiding duplicates (and there are mitigations for teams to consider) but anything that reduces duplication does alleviate the issue quite a bit.
I understand this is not trivial to address, but (whether in pins or through other packages to come) the benefit of avoiding duplication (at least in some use-cases) makes the effort worthwhile.

**Comment by hadley** [comment]
We probably also need to more aggressively advertise `pins::pin_versions_prune()`. `pins_version_prune(n = 20)` would be particularly useful if we can avoid recreating pins with the same timestamp.

**Comment by kmasiello** [comment]
Two helper functions in gist format that may assist for the time being: 

- `[pin_unique](https://gist.github.com/kmasiello/2d47c88617339fa69c85fa3ed8905e86)` will only pin if the data frame is changed from the most recently-pinned version. Optionally incorporates a pruning value to keep things under control.
- `[pin_compare](https://gist.github.com/kmasiello/2d47c88617339fa69c85fa3ed8905e86)` yields the output of `diffdf::diffdf()` on the specified versions of a pin to see changes.

**Comment by juliasilge** [comment]
We have made a change in #735 that addresses this issue, and we would be so happy for any of you to try it out and give feedback! You can install via `remotes::install_github("rstudio/pins-r")`.

The default is now _not_ to write a new version with identical contents, but you can force the write via an optional argument:

``` r
library(pins)
b <- board_connect()
#> Connecting to Posit Connect 2023.03.0 at <https://colorado.posit.co/rsc>

b %>% pin_write(1:10, "julia.silge/my-amazing-numbers")
#> Guessing `type = 'rds'`
#> Writing to pin 'julia.silge/my-amazing-numbers'

b %>% pin_write(1:10, "julia.silge/my-amazing-numbers")
#> Guessing `type = 'rds'`
#> ! The hash of pin "julia.silge/my-amazing-numbers" has not changed.
#> • Your pin will not be stored.

b %>% pin_write(1:10, "julia.silge/my-amazing-numbers", force_identical_write = TRUE)
#> Guessing `type = 'rds'`
#> Writing to pin 'julia.silge/my-amazing-numbers'
```

<sup>Created on 2023-05-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

For now, this new functionality checks the hash of the pin contents _only_; the metadata is not hashed or checked. This would mean that right now you need to do something like this to change the metadata without changing the pin contents:

``` r
library(pins)
b <- board_connect()
#> Connecting to Posit Connect 2023.03.0 at <https://colorado.posit.co/rsc>

b %>% pin_write(
  1:10, 
  "julia.silge/some-amazing-numbers"
)
#> Guessing `type = 'rds'`
#> Writing to pin 'julia.silge/some-amazing-numbers'

## does not successfully write:
b %>% pin_write(
  1:10, 
  "julia.silge/some-amazing-numbers",
  description = "These numbers are amazing!"
)
#> Guessing `type = 'rds'`
#> ! The hash of pin "julia.silge/some-amazing-numbers" has not changed.
#> • Your pin will not be stored.

## will force write:
b %>% pin_write(
  1:10, 
  "julia.silge/some-amazing-numbers", 
  description = "These numbers are amazing!",
  force_identical_write = TRUE
)
#> Guessing `type = 'rds'`
#> Writing to pin 'julia.silge/some-amazing-numbers'
```

<sup>Created on 2023-05-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

We still plan to look at what exactly is stored as `pin_hash` and see if it makes sense to include some portion of the metadata in what is hashed.

**Comment by juliasilge** [comment]
I've outlined the issues with hashing metadata in #739. If you have thoughts on that, please chime in! And if you have further problems or questions, please open a new issue.
