### ISSUE TITLE
Feature Request: Static Remote Directory Naming for Latest Version

### ISSUE THREAD

**Issue by samterfa** [rstudio/pins-r#590]
First, I really like this package. It's so, so helpful, thank you!

I specifically pin data to an AWS S3 bucket. I would like to be able to provide the external file path of my pinned data to other software and have that file path in S3 be static. This may be possible already and I missed it, but to my knowledge, the enclosing directory is a datetime-based format which will change with each new version of the data. board_url is really great but to my knowledge doesn't accept credentials for accessing a private bucket.

If instead the latest or current version of the pinned object were predictably in an enclosing folder named "current_version" or "latest" or something like that, then I could provide that external file path to other software. There could also be some other creative solution that I'm not thinking of.

Thank you for the terrific package!

**Comment by juliasilge** [comment]
Thanks with your patience on this! We are planning on implementing a new `write_board_manifest()` in #661 and then make some changes for `board_url()` to be able to read from boards with a manifest, similar to #650. If you have ideas or thoughts, feel free to chime in on those PRs or in #627.
