### ISSUE TITLE
The code chunk from RStudio Connect doesn't work without modifications

### ISSUE THREAD

**Issue by scherbakovdmitri** [rstudio/pins-r#603]
Hello, 
If I run this code in RStudio:
```
library(pins)
board <- board_rsconnect()
mtcars <- tibble::as_tibble(mtcars)
board %>% pin_write(mtcars, "mtcars")
```

And then open the pin in Connect , it shows this chunk of code:
```
library(pins)
board <- board_rsconnect("envvar", server = "http://10.0.0.15")
pin_read(board, "subsea/mtcars")
```

If I run it I get this:
```
> board <- board_rsconnect("envvar", server = "http://10.0.0.15")
Error in `rsc_server()`:
! Can't find CONNECT_API_KEY env var
```

The chunk that works is this:
```
library(pins)
board <- board_rsconnect(server = "10.0.0.15")
pin_read(board, "subsea/mtcars")
```

Wouldn't it be better to display this one instead? Because if sharing with other users, they can get confused if they see some chunk in Connect which doesn't work right away.

**Comment by juliasilge** [comment]
What if this preview showed code like this:

```r
library(pins)
board <- board_rsconnect()
pin_read(board, "user.name/mtcars")
```

Given [how `board_rsconnect()` works](https://pins.rstudio.com/reference/board_rsconnect.html), this seems mostly like to work for the most folks. Thoughts?

**Comment by juliasilge** [comment]
Thank you for your discussion! 🙌 For now, let's keep displaying the code that aligns with what we recommend for all users on Connect.
