### ISSUE TITLE
Support pin_search on RStudio Connect when user is an admin

### ISSUE THREAD

**Issue by machow** [rstudio/pins-r#606]
See https://github.com/machow/pins-python/issues/27#issuecomment-1075633988

Currently, admin users on RStudio Connect can show a list of all pin content, including content they are not able to access. However, this leads to this bad situation:

* admin user runs pin_search, it
* searches all pins, including those they can't access
* for matching pins, it attempts to access metadata

In order to resolve, we could catch failures to fetch metadata and have them return something with less information (e.g. pin name).

See:

* [where RSC calls multi_meta](https://github.com/rstudio/pins/blob/main/R/board_rsconnect.R#L325), which calls pin_meta, which attempts to fetch data.

**Comment by kmasiello** [comment]
Also posting a reminder that `pin_list()` and `pin_exists()` may be suitable alternatives for users running into this issue, depending on what the use case is for running `pin_search()`.
