### ISSUE TITLE
Pins in RStudio Connect do not show all the metadata available

### ISSUE THREAD

**Issue by chrisumphlett** [rstudio/pins-r#609]
This stems from an issue I opened at the RStudio community: https://community.rstudio.com/t/how-much-physical-memory-is-my-pin-using/131474/2

https://www.screencast.com/t/V8un8z9xxp shows what I see in RSC for old and new versions of `pins`.

I want to see the things that one can view with `pin_meta()`: https://www.screencast.com/t/uTCcWdYjOT

ht to @colearendt

**Comment by machow** [comment]
Hey--can you share some example code for how you were able to `pin_write` the v1 pin on the left of your screencapture? 

AFAIK writing a pin of type table isn't possible, so if I could see how you got it up on RSC, it'd help center in on the problem:

<img width="824" alt="image" src="https://user-images.githubusercontent.com/2574498/162993209-865ef973-29af-4bcc-9a5e-b46f17b513e9.png">

**Comment by chrisumphlett** [comment]
Sure. I've never used the `type` parameter. BTW, this runs in a .Rmd deployed on RSC.

```
pin(my_data_frame,
    description = "my description",
    board = "rsconnect"
)
```

**Comment by machow** [comment]
Ah, thanks! If you switch to use `pin_write` instead...

```R
pin_write(
    my_data_frame,
    description = "my description",
    board = "rsconnect"
)
```

Does it show the preview and file size?

![image](https://user-images.githubusercontent.com/2574498/162995801-958cdd6e-6d8b-47e0-9022-69a612ca583c.png)

**Comment by chrisumphlett** [comment]
@machow I reminded myself of why I had stuck with `pin` before... this has broken my shiny app that was using the pin. I am having a hard time connecting to it.
Problem #1, which I solved: the name of the pin gets switched from using hyphens to underscores.
Problem #2, I can successfully connect in my Shiny app when deployed on RSC, but the app running locally gets an error: 
```
Error: [ENOENT] Failed to search directory 'C:/Users/{redacted - some non-sense string}/AppData/Local/pins/pins/Cache/rsc-{redacted string}/{redacted string}': no such file or directory
```
Why is it searching locally instead of on the RSC board?

**Comment by chrisumphlett** [comment]
I was already using `pin_read()`

**Comment by chrisumphlett** [comment]
I'm not sure about a reprex, given this may be some environment-specific problem I'm having. Here's how I retrieve:

`new_df <- pin_read(board, "account/pin-name")`

**Comment by chrisumphlett** [comment]
```
> traceback()
14: (function (..., call. = TRUE, domain = NULL) 
    {
        if (...length() == 1L && inherits(..1, "condition")) {
            cond <- ..1
            if (nargs() > 1L) 
                warning("additional arguments ignored in stop()")
            message <- conditionMessage(cond)
            call <- conditionCall(cond)
            .Internal(.signalCondition(cond, message, call))
            .Internal(.dfltStop(message, call))
        }
        else .Internal(stop(call., .makeMessage(..., domain = domain)))
    })(structure(list(message = "[ENOENT] Failed to search directory 'C:/Users/{redacted}': no such file or directory"), class = c("ENOENT", 
    "fs_error", "error", "condition"), location = "dir.cc:89"))
13: dir_map(old, identity, all, recurse, type, fail)
12: fs::dir_ls(fs::path(board$cache, guid))
11: rsc_content_version_cached(board, guid)
10: value[[3L]](cond)
9: tryCatchOne(expr, names, parentenv, handlers[[1L]])
8: tryCatchList(expr, classes, parentenv, handlers)
7: tryCatch(rsc_content_version_live(board, guid), error = function(cnd) {
       rsc_content_version_cached(board, guid)
   })
6: rsc_content_version(board, content$guid)
5: pin_meta.pins_board_rsconnect(board, name, version = version)
4: pin_meta(board, name, version = version)
3: pin_fetch.pins_board_rsconnect(board, name, version = version, 
       ...)
2: pin_fetch(board, name, version = version, ...)
1: pin_read(board, "account/pin")
```

**Comment by machow** [comment]
It looks like you're using board_rsconnect's use_cache_on_failure (which is set to TRUE when using R interactively). I wonder if...

* it's having issues connecting to RSC, so
* it falls back to trying your local cache
* because the content hasn't been accessed (and cached), it errors

It seems like the error message could be a bit more informative 😬. Can you try setting `use_cache_on_failure=FALSE` in `board_rsconnect`? I think it might still error, but might make it easier to tell whether it's erroring because it can't connect to your RSC instance

**Comment by chrisumphlett** [comment]
Get this error:
```
Error: RStudio Connect API failed [404]
* The requested object does not exist.
```

**Comment by machow** [comment]
Can you post the code that is giving that error?

**Comment by chrisumphlett** [comment]
Here's everything related to reading the pins. The only thing I changed, from what I had before, is indicated with my comments `#removed` or `#added`.

```
library(pins)
httr::set_config(httr::config(ssl_verifypeer = FALSE, ssl_verifyhost = FALSE))
board_server <- if_else(.Platform$OS.type == "windows", "{our RSC url}", "https://{our RSC url}")
pin_rsc_board_key <- Sys.getenv("pin_rsc_board_key")
board <- board_rsconnect(use_cache_on_failure = FALSE) #added
# board <- board_rsconnect(auth = "manual", key = pin_rsc_board_key, server = board_server) #removed
# board_register_rsconnect(                                            #removed
#   account = "my-account",
#   key = Sys.getenv("pin_rsc_board_key"),
#   server = board_server
# )

my-df<- pin_read(board, "my-account/my-pin")
```

**Comment by machow** [comment]
Can you do things like `pin_list(board)` etc..?

**Comment by machow** [comment]
Hmm.. that's really strange--I wonder if the pin's metadata lists a file that doesn't exist for some reason. What happens if you use `pin_meta` to get metadata for the pin that caused the 404? If you can post the metadata output, I think we've nearly got things narrowed down......

**Comment by machow** [comment]
If you pin_write and pin_read using a different name for the pin, does it work? I wonder if one thing that could help is deleting your `board$cache` folder (you may need to run `board_rsconnect` again after that).

Here's the output I see for my rsc cache:

```R
> board$cache
~/Library/Caches/pins/rsc-e62371cfd77db754024f9c5ed3556a73
```

(cc @colearendt , in case you've seen something like this?)

**Comment by chrisumphlett** [comment]
Yea just adding a '2' to the name of the pin and it works with the full reference to the pin name.
Manually deleting the cache folder, and now I can use the original (full) name. Thanks for that suggestion

**Comment by chrisumphlett** [comment]
no intentional changes, I am the only one who has written the pin. I had to change my password recently (we use SSO with RSC) which caused various kinds of havoc, that's the only kind of change I can think of.
