### ISSUE TITLE
Unable to load data stored with pins on rstudio connect

### ISSUE THREAD

**Issue by yacaslimi** [rstudio/pins-r#622]
Hello,

I'm currently working with the package pins. I am an RSW user with the following configuration:

R version 4.1.3 (2022-03-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.6 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached are base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] pins_1.0.1 yaml_2.3.5

loaded via a namespace (and not attached):
 [1] fansi_1.0.3      digest_0.6.29    utf8_1.2.2       crayon_1.5.1     rappdirs_0.3.3   R6_2.5.1        
 [7] jsonlite_1.8.0   lifecycle_1.0.1  magrittr_2.0.3   httr_1.4.3       pillar_1.7.0     rlang_1.0.2     
[13] cli_3.3.0        curl_4.3.2       rstudioapi_0.13  fs_1.5.2         vctrs_0.4.1      ellipsis_0.3.2  
[19] tools_4.1.3      glue_1.6.2       rsconnect_0.8.26 compiler_4.1.3   askpass_1.1      pkgconfig_2.0.3 
[25] openssl_2.0.2    tibble_3.1.7

I managed to push datasets on R Studio connect with pins. 
![image](https://user-images.githubusercontent.com/105648250/175351376-ce752f1e-a9ad-4ab0-a756-c21788543921.png)

Now I'd like to use one of that datasets on RSW.  I am able to connect on RsStudio connect with the command:
> board_rsconnect()

However, when I tried to load one of the datasets by using:

> pin_read(board, "earth2") 

It doesn't load the data. Instead, there is the following message:

        Error in yaml.load(string, error.label = error.label, ...) : 
          (~/.cache/pins/rsc-e62371cfd77db754024f9c5ed3556a73/51ca356e-619e-4148-b12f-35e3e652d14d/79/data.txt) Scanner error: mapping values are not allowed in this context at line 36, column 20955
        In addition: Warning message:
        In readLines(file, warn = readLines.warn) :
          incomplete final line found on '~/.cache/pins/rsc-e62371cfd77db754024f9c5ed3556a73/51ca356e-619e-4148-b12f-35e3e652d14d/79/data.txt'
 

By searching similar issues, someone has achieved to load it by deleting the data.txt file but it failed for me.  https://github.com/rstudio/pins/issues/463
Do you know where the error came from?

**Comment by yacaslimi** [comment]
Hello everyone,

I tried to load data with pins using the previous versions ie 1.0.0 and 0.4.5 but it failed too. Is that functionality (read data from Rconnect on RSW) still supported?

**Comment by machow** [comment]
Hey -- this particular error seems to be a yaml parsing error. Could you try deleting the cache and then reading the pin?

You can remove this folder

```
~/.cache/pins/rsc-e62371cfd77db754024f9c5ed3556a73/
```

or run

```
# delete all caches
cache_prune(days=0)
```

**Comment by yacaslimi** [comment]
Hello @machow,

Thanks for your reply. I started with the removing of the folder **rsc-e62371cfd77db754024f9c5ed3556a73/**
![image](https://user-images.githubusercontent.com/105648250/175606356-a26ef6fe-156d-46a3-bbf5-fd0c0b6d3e7e.png)
 but it doesn't solve the issue. 
![image](https://user-images.githubusercontent.com/105648250/175606887-9a60e821-72cf-429b-8a1f-bf912126dfc1.png)

I also tried to delete all caches and relaunch the **pin_read()** command but without success:

![image](https://user-images.githubusercontent.com/105648250/175607392-f15eb209-a16e-4b50-864c-19ff50fea93f.png)


About the data.txt file, it is a long one. I can't get the top of it from the R terminal but this is an HTML file:

          
![image](https://user-images.githubusercontent.com/105648250/175608712-0b2cc434-ff77-4d0d-a10e-361d53214505.png)

      
and it finish by 
![image](https://user-images.githubusercontent.com/105648250/175608795-1c02d2a4-8916-4537-b081-220f39e0835e.png)

**Comment by machow** [comment]
Is that HTML file you posted a picture of the contents of data.txt?

**Comment by yacaslimi** [comment]
Yes, absolutely.

**Comment by yacaslimi** [comment]
An update about this topic:

I tried to bypass the *pin_read* function. I used the function *read.csv* with the URL to the dataset pins on rconnect instead of the *pin_read* function. Sadly, it didn't work.

I also used *download.files()* function go get the dataset on my working environment on RSW but I got an HTML instead. The HTML is associated with the authentification to the active directory of the company. (login/password etc...). 

The file is the same that data.txt in the cache. What I didn't understand for the moment, is how can I write pins on rsconnect without problem but when I tried to read the file on the same rstudio connect, I get that HTML login file.

**Comment by yacaslimi** [comment]
Hello @machow,

Thanks for your reply. This is the output of the previous command. I just hid the server URL and the name.
      > with_verbose(pin_read(board, "*****************/mtcars3"))
      -> GET /__api__/v1/content/de880b93-2bda-4c0d-bcf7-a5a52e031385 HTTP/1.1
      -> Host: rs-connect.*****************************************************
      -> User-Agent: libcurl/7.58.0 r-curl/4.3.2 httr/1.4.3
      -> Accept-Encoding: deflate, gzip
      -> Cookie: rscid=MTY1NjM1NTUzNXxEdi1CQkFFQ180SUFBUkFCRUFBQU52LUNBQU1HYzNSeWFXNW5EQVlBQkVkVlNVUVNZMjl1Ym1WamRDOXpkRzl5WlM1SFZVbEVfNE1HQVFFRVIxVkpSQUhfaEFBQUFCRF9oUVlCQVFSVlZVbEVBZi1HQUFBQVZmLUVFZ0FRbHBNM2dYQ0xRRDJUeDBzelY3elkxUVp6ZEhKcGJtY01DUUFIWTNKbFlYUmxaQVZwYm5RMk5BUUdBUHpGY19XZUJuTjBjbWx1Wnd3SkFBZHlaV1p5WlhOb0JXbHVkRFkwQkFZQV9NVno5WjQ9fJMOpB3VzVkYX4XoDItiltamtV8tAWKxcrM_gLYRjVPq; rscid-legacy=MTY1NjM1NTUzNXxEdi1CQkFFQ180SUFBUkFCRUFBQU52LUNBQU1HYzNSeWFXNW5EQVlBQkVkVlNVUVNZMjl1Ym1WamRDOXpkRzl5WlM1SFZVbEVfNE1HQVFFRVIxVkpSQUhfaEFBQUFCRF9oUVlCQVFSVlZVbEVBZi1HQUFBQVZmLUVFZ0FRbHBNM2dYQ0xRRDJUeDBzelY3elkxUVp6ZEhKcGJtY01DUUFIWTNKbFlYUmxaQVZwYm5RMk5BUUdBUHpGY19XZUJuTjBjbWx1Wnd3SkFBZHlaV1p5WlhOb0JXbHVkRFkwQkFZQV9NVno5WjQ9fJMOpB3VzVkYX4XoDItiltamtV8tAWKxcrM_gLYRjVPq
      -> Accept: application/json, text/xml, application/xml, */*
      -> Date: Mon, 27 Jun 2022 18:47:23 GMT
      -> X-Auth-Token: T3ad3753787697852f3230602569c29ca
      -> X-Auth-Signature: EzxlHKNhJVXGad0NM+XsdViLCbnxXf+W8MrnWXp3KHPZlFuXH3cKbG4ug/835fHVlHlg+Pu71cRUMF0gk3run/7srRj1GCOmIUtfXYYkFMDQxPyHcZQES3hyHPSBhEIVvSJj0Gmg/kSE/CqYSAJFUjS97Uee7ifuc1rhlC4H4CYVEPpllNl945VSfNCWrX6O2hl6H1rOgH5JumsArqeO/uT3gfwPVoyjz97YTQ/Ins5LmWtbbV4cp/8A3h3Veqw1g75LFleJsTpOGde2YCPEqfwA+7w9M1gJM4X1M5p8+eJC/EjJmffOFdJfqR5x+P2dM0BWhiUTaCVp/GBs6eO8Vw==
      -> X-Content-Checksum: 1B2M2Y8AsgTpgAmY7PhCfg==
      -> 
      <- HTTP/1.1 200 OK
      <- Server: nginx/1.18.0 (Ubuntu)
      <- Date: Mon, 27 Jun 2022 18:47:23 GMT
      <- Content-Type: application/json; charset=utf-8
      <- Content-Length: 949
      <- Connection: keep-alive
      <- Cache-Control: no-cache, no-store, must-revalidate
      <- Expires: 0
      <- Pragma: no-cache
      <- Strict-Transport-Security: max-age=2592000
      <- X-Content-Type-Options: nosniff
      <- X-Correlation-Id: 0e74ed12-189f-4999-9f3e-bf1d63c46ba7
      <- X-Frame-Options: DENY
      <- 
      Error in yaml.load(string, error.label = error.label, ...) : 
        (~/.cache/pins/rsc-e62371cfd77db754024f9c5ed3556a73/de880b93-2bda-4c0d-bcf7-a5a52e031385/100/data.txt) Scanner error: mapping values are not allowed in this context at line 36, column 21045
      In addition: Warning message:
      In readLines(file) :
        incomplete final line found on '~/.cache/pins/rsc-e62371cfd77db754024f9c5ed3556a73/de880b93-2bda-4c0d-bcf7-a5a52e031385/100/data.txt'


Hope this helps you :)

**Comment by machow** [comment]
Thanks--it looks like it is trying to do a redirect to login.microsoftonline.com, but I'm not sure why :/.

What happens if you open RSC in the browser, and then paste the URL for retrieving `data.txt` file directly?

```
<your board server url>/content/de880b93-2bda-4c0d-bcf7-a5a52e031385/_rev100/data.txt
```

For example, here's what I get when I do something similar with an internal testing server:

<img width="889" alt="image" src="https://user-images.githubusercontent.com/2574498/176030569-6973f8b1-7626-4997-873f-694f39a37157.png">

**Comment by yacaslimi** [comment]
@machow: Yes, I get this metadata about the dataset *mtcars3*:

![image](https://user-images.githubusercontent.com/105648250/176053552-5861a3bb-5514-4e22-9063-4e122ea3bf7d.png)

@sellorm: Yes, not sure about that. I'll check this point with the IT service tomorrow. 
Thanks a lot for your help.

**Comment by sellorm** [comment]
Thanks for the update @yacaslimi.

In cases where I've seen this before the IT team has been able to temporarily disable the WAF to confirm the issue and then reenable it with new or edited WAF rules to allow the appropriate API request(s), which has fixed the issue.

I hope you manage to get this resolved and please let us know if we can be of further assistance.
