### ISSUE TITLE
arrow to Suggests?

### ISSUE THREAD

**Issue by jonthegeek** [rstudio/pins-r#644]
If you're reading and writing json or rds, `{arrow}` can be a relatively heavy, unused dependency. Would it be possible to move it to suggests? I'm not sure how tricky that might be (for example, to anticipate what types might need to be read), so I understand if this isn't feasible. I'm just seeing what I can cut out to make my containers a little smaller!

**Comment by juliasilge** [comment]
Related to #537 where we discussed this before

**Comment by jonthegeek** [comment]
The `NOT_CRAN=TRUE` suggestion in there (and in `arrow`'s docs) didn't stop my lambda docker image from building from source, FWIW. Hopefully soon AWS will update those images to their new Amazon Linux 2022, which would probably make this less painful, but as it is installation is slow.

But really my issue with it is that it's a complicated installation that I don't use. I'm trying to reduce the warm up time on this lambda, and every little thing that I can cut out of the image could potentially help with that.

**Comment by juliasilge** [comment]
Let's do this 👍 

Do you want to contribute a PR @jonthegeek? We would want to make a little pair of helper functions that work just like `read_qs()` and `write_qs()`, and of course move arrow to Suggests.

**Comment by jonthegeek** [comment]
I'll look into it soon (if nobody beats me to it), @juliasilge. I haven't dug into the pins code yet so I'm not sure how confused I'll get when I do 🙃

**Comment by jonthegeek** [comment]
Oh, this is way more straightforward than I thought, PR coming soon!
