### ISSUE TITLE
`pin_write()` does not always return fully qualified path as documented

### ISSUE THREAD

**Issue by juliasilge** [rstudio/pins-r#647]
As @jonthegeek points out in #646 `object_write()` does not always return the path. Sometimes it returns the object.

**Comment by juliasilge** [comment]
Wait, is this wrong? It does always return the path, doesn't it?

https://github.com/rstudio/pins-r/blob/b8ea052113fb40ebfbf72b6ef98b8b21ba51489a/R/pin-read-write.R#L135

**Comment by jonthegeek** [comment]
Huh, I think I misread it. I thought it was returning what the sub-function returns, but it ignores that... so I think you're all set!

**Comment by juliasilge** [comment]
We actually _are_ testing this, via the `local_pin()` function:

https://github.com/rstudio/pins-r/blob/b8ea052113fb40ebfbf72b6ef98b8b21ba51489a/R/testthat.R#L2

That function is called in all the tests that run across boards, including the metadata tests like `test_api_meta()`. We are definitely good to go. 👍
