### ISSUE TITLE
board_s3, Shiny deployment, and paws dependency

### ISSUE THREAD

**Issue by vgXhc** [rstudio/pins-r#673]
I just walked through this issue with shinyapps.io support, and I think this qualifies as a {{pins}} issue:

I have a Shiny app that uses `board_s3` to read in data. Reprex (if you provide your own S3 credentials)

```
library(pins)
board <- board_s3("vzpins",
region = "us-east-1",
access_key = Sys.getenv("S3_ACCESS_KEY"),
secret_access_key = Sys.getenv("S3_SECRET_ACCESS_KEY"))

# Define UI for application that draws a histogram
ui <- fluidPage(

# Application title
titlePanel("Old Faithful Geyser Data"),

# Sidebar with a slider input for number of bins
sidebarLayout(
sidebarPanel(
sliderInput("bins",
"Number of bins:",
min = 1,
max = 50,
value = 30)
),

# Show a plot of the generated distribution
mainPanel(
plotOutput("distPlot")
)
)
)

# Define server logic required to draw a histogram
server <- function(input, output) {

output$distPlot <- renderPlot({
# generate bins based on input$bins from ui.R
x <- faithful[, 2]
bins <- seq(min(x), max(x), length.out = input$bins + 1)

# draw the histogram with the specified number of bins
hist(x, breaks = bins, col = 'darkgray', border = 'white')
})
}

# Run the application
shinyApp(ui = ui, server = server)
```

The app worked fine locally, but after deploying it on shinyapps.io I got a (not very helpful) error:

```
022-10-19T15:19:22.316043+00:00 shinyapps[6862336]: Error in value[[3L]](cond) :
2022-10-19T15:19:22.316075+00:00 shinyapps[6862336]: Calls: local ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
2022-10-19T15:19:22.316080+00:00 shinyapps[6862336]: Execution halted
2022-10-19T15:19:22.316096+00:00 shinyapps[6862336]: Shiny application exiting ...
```

Long story short, we ultimately identified the issue: When deploying the app with `rsconnect()`, only imported package dependencies are  included in the bundle; suggested packages are not. `board_s3` relies on `paws.storage`, which is apparently not a required package. Including `library(paws.storage)` in the code of the app made it work:

`````
library(pins)
library(paws.storage)
board <- board_s3("vzpins",
region = "us-east-1",
access_key = Sys.getenv("S3_ACCESS_KEY"),
secret_access_key = Sys.getenv("S3_SECRET_ACCESS_KEY"))

# Define UI for application that draws a histogram
ui <- fluidPage(

# Application title
titlePanel("Old Faithful Geyser Data"),

# Sidebar with a slider input for number of bins
sidebarLayout(
sidebarPanel(
sliderInput("bins",
"Number of bins:",
min = 1,
max = 50,
value = 30)
),

# Show a plot of the generated distribution
mainPanel(
plotOutput("distPlot")
)
)
)

# Define server logic required to draw a histogram
server <- function(input, output) {

output$distPlot <- renderPlot({
# generate bins based on input$bins from ui.R
x <- faithful[, 2]
bins <- seq(min(x), max(x), length.out = input$bins + 1)

# draw the histogram with the specified number of bins
hist(x, breaks = bins, col = 'darkgray', border = 'white')
})
}

# Run the application
shinyApp(ui = ui, server = server)
`````

So maybe there's a way to explicitly include the `paws.storage` as required. Or at least a note about this issue somewhere in the documentation.

**Comment by juliasilge** [comment]
This is related to rstudio/vetiver-r#149, where I asked whether pins needs to have a [concept of `required_pkgs` for boards](https://generics.r-lib.org/reference/required_pkgs.html), much like tidymodels model objects do:

``` r
library(parsnip)
rand_forest() %>% required_pkgs()
#> [1] "parsnip" "ranger"
```

<sup>Created on 2022-11-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

This will help with building Dockerfiles and such, but I don't think would help with building an app that does the dependency sniffing the way that the rsconnect package does; that explicitly requires you to use `library(paws.storage)` or `paws.storage::s3()` for the dependency to be picked up. I think the best we can do for that case is document this better. Right now the [documentation says this](https://pins.rstudio.com/reference/board_s3.html):

> Pin data to a bucket on Amazon's S3 service, using the paws.storage package.

What do you think would have been more helpful to you here, to understand this board uses paws.storage?

**Comment by vgXhc** [comment]
Thanks for the response.

> What do you think would have been more helpful to you here, to understand this board uses paws.storage?

Hm, good question. I guess I read "uses the paws.storage package" as "you need to have the package installed" and not as "you need to include `library("paws.storage")` in your code." I'm very used to R packages handling dependencies without me ever having to worry about them...

The fact that the code worked fine locally and the issue only appeared after deploying the app probably also led me down the wrong path in troubleshooting. (I don't have a good concept of what happens when I push the "publish app" button in RStudio). So I'm not really sure what language would be better. Is there maybe a way to create a more meaningful error message?

**Comment by juliasilge** [comment]
Thank you for your thoughts @vgXhc! 🙌 

We are taking a couple of steps to improve this situation:

- We have one ticket open internally to fix how errors are surfaced on Connect/shinyapps.io so that someone like you gets a more useful message. The idea is that instead of cryptic "Error in value[[3L]](cond) ..." you would see something in the logs like "The paws.storage package is required".
- We have another ticket open internally to develop better documentation for how automatic dependency discovery happens. For now, we are [going to link to this](https://support.posit.co/hc/en-us/articles/229998627-Why-does-my-app-work-locally-but-not-on-my-RStudio-Connect-server) but we plan to make something more focused and clear, specifically about the dependency discovery.
- In #675 I added documentation to pins itself to highlight this behavior. You can [see it rendered here for `board_s3()`](https://pins.rstudio.com/dev/reference/board_s3.html#details).

Thank you again for sharing what happened in your situation! 🙏
