### ISSUE TITLE
Having an argument "read_only" for "board" functions

### ISSUE THREAD

**Issue by Sade154** [rstudio/pins-r#684]
It would be nice to have an argument read_only to make sure that we dont alterate our data products when manipulating pins :

```board_local(..., read_only = TRUE)```

**Comment by juliasilge** [comment]
Thanks for the suggestion @Sade154! 🙌 We current turn off/on reading methods based off the class of the board, like so:

https://github.com/rstudio/pins-r/blob/95af5586bed14607caaea5610d438ad653793d7a/R/board_url.R#L134-L136

I think the kind of change you suggest would involve new classes of boards (like subclasses). Let's keep this issue open for understanding how important this feature could be and prioritizing it.
