### ISSUE TITLE
More helpful error message for new users to specify the right server to connect to

### ISSUE THREAD

**Issue by RachaelDempsey** [rstudio/pins-r#702]
When trying to connect for the first time, I was using: board <- pins::board_rsconnect()

I received the following error:
! Found multiple matching RStudio Connect servers
ℹ Please disambiguate with `server` and/or `account`
Backtrace:
 1. pins::board_rsconnect()
 2. pins:::rsc_server(auth, server, account, key)
 3. pins:::rsc_server_rsconnect(server, account)

Hadley recommended running rsconnect::accounts() and I was able to see the server name I should be using.

A helpful error message pops up when you run:
board_rsconnect(server = "server name")

But not when you run:
board <- pins::board_rsconnect()

**Comment by juliasilge** [comment]
In a totally fresh environment, I see a different error:

``` r
b <- pins::board_rsconnect()
#> Error in `check_auth()`:
#> ! auth = `auto` has failed to find a way to authenticate:
#> • `server` and `key` not provided for `auth = 'manual'`
#> • Can't find CONNECT_SERVER and CONNECT_API_KEY envvars for `auth = 'envvar'`
#> • rsconnect package not installed for `auth = 'rsconnect'`

#> Backtrace:
#>     ▆
#>  1. └─pins::board_rsconnect()
#>  2.   └─pins:::rsc_server(auth, server, account, key)
#>  3.     └─pins:::check_auth(auth, server, key)
#>  4.       └─rlang::abort(...)
```

<sup>Created on 2023-01-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Do you think you can give a little more info on what the status of your environment variables (set, not set, etc) and such are?

**Comment by Chas-RST-2022** [comment]
Adding ticket https://rstudioide.zendesk.com/agent/tickets/87842 

"The weird error message threw me a bit – it seemed to be related to the
 (https://support.posit.co/hc/requests/86727) ticket where the server did not want not connect to URL on the same server.

I tried your suggestion of the environment variable. And it worked fine.
What bugged me was that I could not recall using a CONNECT_API_KEY before for any pins which I published to Connect before.  I’ve figured that using board_rsconnect() can explain that, as the defining the CONNECT_API_KEY is then not required, 

I.e
board <- board_connect(
     server = "connect.novus3.co.za",
     auth = "envvar"
     )
Can just become on Posit Connect
board <- board_rsconnect()
to make it work locally, it should bet
board <- board_rsconnect(
server = "connect.novus3.co.za"
     )

**None of the above is clear when deploying to a Posit Connect server, given the following error message.**
A request to improve the error trapping should be passed on to your Connect development team.  
Will you please do so?"

**Comment by Chas-RST-2022** [comment]
@juliasilge My apologies for not adding the error message.                                                                                                                                                                                                                                                                                    
I updated my posting with the error.

**Comment by juliasilge** [comment]
In a fresh session, I see a different error:

``` r
library(pins)
board_connect(server = "connect.example.com")
#> Error in `check_auth()`:
#> ! auth = `auto` has failed to find a way to authenticate:
#> • `server` and `key` not provided for `auth = 'manual'`
#> • Can't find CONNECT_SERVER and CONNECT_API_KEY envvars for `auth = 'envvar'`
#> • rsconnect package not installed for `auth = 'rsconnect'`
#> Backtrace:
#>     ▆
#>  1. └─pins::board_connect(server = "connect.example.com")
#>  2.   └─pins:::rsc_server(auth, server, account, key)
#>  3.     └─pins:::check_auth(auth, server, key)
#>  4.       └─rlang::abort(...)
```

<sup>Created on 2023-04-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

This is the error that pins gives when it can't find a way to authenticate. To understand more about what is leading to the confusing error reported above, I need a little more info on what the status of the environment variables (set, not set, etc) and such are. I suspect that this is an error coming from Connect, not from pins.

**Comment by juliasilge** [comment]
Let me know if you run into this again or are able to share more about the situation in which this error comes up! 🙌
