### ISSUE TITLE
! Posit Connect API failed [401]

### ISSUE THREAD

**Issue by tsharaf** [rstudio/pins-r#708]
I have a RMarkdown file that runs on schedule on Posit Connect every hour. The job writes a Pin to Posit with new dataframe. 

I am getting Posit Connect API failed [401] few of the 24 times this task is supposed to run and when I check the log I get the following:

Error in `rsc_check_status()`:
02/13 21:23:29.270 (GMT)
! Posit Connect API failed [401]
02/13 21:23:29.309 (GMT)
• We couldn't log you in with the provided credentials. Please ask your administrator for assistance.
02/13 21:23:29.309 (GMT)
Backtrace:
02/13 21:23:29.309 (GMT)
1. pins::pin_write(...)
02/13 21:23:29.309 (GMT)
3. pins:::pin_store.pins_board_connect(...)
02/13 21:23:29.309 (GMT)
4. pins:::rsc_GET(board, rsc_v1("tasks", task_id), list(wait = 1))
02/13 21:23:29.309 (GMT)
5. pins:::rsc_check_status(req)

I am unable to figure out why the same file runs fines with same credentials and other it gives an error.
I am using Pins 1.1.0 and connecting to Posit Connect using board_connect with my account and API key.

The error takes place when using pin_write

**Comment by juliasilge** [comment]
Let us know if you have any further problems!

**Comment by dareneiri** [comment]
@tsharaf Just wanted to let you know I've had a very similar issue (same error related to authentication), but haven't been able to properly debug it. Also using Connect to store and retrieve pins, and it happens seemingly random.

**Comment by tsharaf** [comment]
@dareneiri  I have contacted Posit Connect and they recommend to add the following line in my document: 

`httr::set_config(config(ssl_verifypeer = FALSE, ssl_verifyhost = FALSE)) `

and so far the document is running without any issues
