### ISSUE TITLE
Should pins support parquet?

### ISSUE THREAD

**Issue by hadley** [rstudio/pins-r#713]
Maybe in preference to arrow? I think that it would be easier to argue that it should be the default for data frames (#666).

**Comment by juliasilge** [comment]
I keep getting confused about the difference between Arrow and Parquet so let me [add this here](https://arrow.apache.org/blog/2022/10/05/arrow-parquet-encoding-part-1/):

> Arrow is primarily an in-memory format, whereas Parquet is a storage format.

**Comment by juliasilge** [comment]
In pins for Python, we have [`type = "parquet"`](https://github.com/rstudio/pins-python/blob/main/pins/drivers.py#L89) already. Check out [the supported types for writing in the docs](https://rstudio.github.io/pins-python/api/api_card/pins.boards.BaseBoard.pin_write.html#pins.boards.BaseBoard.pin_write).
