### ISSUE TITLE
Feature Request: read_pins supporting nthreads for qs file types

### ISSUE THREAD

**Issue by MichaelSchatz** [rstudio/pins-r#725]
I'd like to be able to take advantage of qs multithreading to read/write pins. However there does not appear to currently be a way to pass in the nthreads argument which qs::qread and qsave use when using pins::pin_read()/pin_write() . 

Am i correct that there is currently no way to pass in that argument? Is that a feature there could be added to future release?

**Comment by juliasilge** [comment]
The dots in `pin_read()` and `pin_write()` are passed through to the method for the _board_ (so for example, you can pass args specific for S3 or Connect through) and not (unfortunately for this request) [through to `object_write()`](https://github.com/rstudio/pins-r/blob/57c4206182ebf7cb9c4125e415886773ae8a6f85/R/pin-read-write.R#L130-L144) or `object_read()`. We are pretty confident that is the best option overall, so what we recommend is that you use `pin_download()` like [this vignette](https://pins.rstudio.com/articles/managing-custom-formats.html) demonstrates. You could write a wrapper function like this:

```r
pin_upload_qs_nthreads <- function(board, x, name, nthreads = 1,  ...) {
  # path deleted when this function exits:
  path <- fs::path_temp()
  withr::defer(fs::file_delete(path))
 
  # custom writer
  qs::qsave(x, path, nthreads = nthreads)

  pin_upload(board, paths = path, name = name, ...) 
}
```

To read you could do it with these steps (maybe easy enough that a wrapper function doesn't help you much):

``` r
library(pins)
b <- board_temp()

# could use a wrapper function as above to *write* with `nthreads`:
b %>% pin_write(1:10, "really-nice-numbers", type = "qs")
#> Creating new version '20230302T175447Z-d86e8'
#> Writing to pin 'really-nice-numbers'

b %>% 
  pin_download("really-nice-numbers") %>%
  qs::qread(strict = TRUE, nthreads = 4)
#>  [1]  1  2  3  4  5  6  7  8  9 10
```

<sup>Created on 2023-03-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by MichaelSchatz** [comment]
Thanks for the quick response! That pattern seems to work well for my use case.
