### ISSUE TITLE
Use pin_read() without username 

### ISSUE THREAD

**Issue by moturoa** [rstudio/pins-r#750]
I would like to make a `pin` "globally" available to all shiny apps on our posit connect server, regardless of the user who wrote it.

Now:
```
pin_write(board, mydata, "my_global_data")
data <- pin_read(board, "myusername/my_global_data")
```

Is it possible to read "my_global_data" regardless of who wrote the pin?

**Comment by juliasilge** [comment]
Yes! You can do this by setting a vanity URL for your pin on Connect:
https://docs.posit.co/connect/user/content-settings/#custom-url
And then having folks read your pin with `board_connect_url()`:
https://pins.rstudio.com/reference/board_connect_url.html

That type of board can only be used for _reading_ and can only read the latest version. You can read a bit more about it [in our latest blog post](https://posit.co/blog/announcing-pins-1-2-0/).
