### ISSUE TITLE
`pin_write()` cannot set `access_type` on an update for Connect

### ISSUE THREAD

**Issue by colearendt** [rstudio/pins-r#760]
If a pin already exists, `update` fails when setting `access_type`, presumably because `find()` or some other method is called with the argument, and the argument is not used.

```
2023/07/31 2:37:38 PM: Quitting from lines 13-18 [unnamed-chunk-1] (rmd_document.Rmd)
2023/07/31 2:37:38 PM: Error in `pin_write()`:
2023/07/31 2:37:38 PM: ! Arguments in `...` must be used.
2023/07/31 2:37:38 PM: ✖ Problematic argument:
2023/07/31 2:37:38 PM: • access_type = "logged_in"
2023/07/31 2:37:38 PM: ℹ Did you misspell an argument name?
2023/07/31 2:37:38 PM: Backtrace:
2023/07/31 2:37:38 PM: 1. global refresh_pin()
2023/07/31 2:37:38 PM: 3. pins::pin_write(., leads_with_eval, name = "jss/pin_name", access_type = "logged_in")
2023/07/31 2:37:38 PM: Execution halted
```

@jspiewak

**Comment by jspiewak** [comment]
Possible this was introduced by #735, where if the hash is the same the function returns before consuming the `...`.
Except the error with the ellipsis obscures the message about the hash being the same.
On the other hand, my R is only so so, so perhaps I am misreading the code.

**Comment by jspiewak** [comment]
Seems like my read is accurate. I passed `force_identical_write = TRUE` in additional to the `access_type` and the error goes away.

**Comment by juliasilge** [comment]
> Except the error with the ellipsis obscures the message about the hash being the same

Are you saying you didn't see the message about the hash being the same at all? Or rather that it was hard to pick out what was going on with multiple messages here?
