### ISSUE TITLE
removing old pins versions

### ISSUE THREAD

**Issue by rkb965** [rstudio/pins-r#772]
Hi, all!

I was under the impression that it was not possible to remove old pins versions based on this sentence in Getting Started:

https://github.com/rstudio/pins-r/blob/8e5013923736a5a4f7f75decc7a335d4089bffe2/vignettes/pins.Rmd#L160

but I learned today about `pin_version_delete()`. 

Is the documentation outdated (possibly true? It looks like that sentence in the documentation is from April 2021 and the function is from May 2021)? Or is there a distinction that I do not understand (also very, very possibly true -- I have only barely started to dip my toes into {pins})?

Thanks!

**Comment by juliasilge** [comment]
You are totally right @rkb965! If you have any feedback about the changes in #773, feel free to leave suggestions.

**Comment by rkb965** [comment]
Lovely, thanks for the clarification, @juliasilge! The docs all look great — I just need to read a few more of them and start actually using :)

**Comment by juliasilge** [comment]
@rkb965 Please let us know if you run into further questions!
