### ISSUE TITLE
Setting Posit Connect Sharing settings

### ISSUE THREAD

**Issue by craigcerto** [rstudio/pins-r#791]
Hi,

I am wondering if it's possible when using pin_upload to set by default the sharing settings for a Pin to be "Anyone - no login required" or "All users - login required"?

I have a process that uploads some log files to a Posit Connect pin board and would like everyone within the server to have download access to the log files without having to manually change the sharing settings for each pin.

Thank you!

**Comment by juliasilge** [comment]
Yes! If your Posit Connect instance allows it, you can share a pin publicly by setting `access_type = "all"` when you write or upload:

``` r
library(pins)

board <- board_connect()
#> Connecting to Posit Connect 2023.07.0 at <https://colorado.posit.co/rsc>
board |> pin_write(
    1:10, 
    "snazzy-numbers", 
    type = "json", 
    access_type = "all"
)
#> Writing to pin 'julia.silge/snazzy-numbers'

path <- fs::path_temp("some-letters.txt")
readr::write_lines(sample(LETTERS, size = 20), path)
pin_upload(
    board, 
    paths = path, 
    name = "snazzy-letters", 
    access_type = "all"
)
```

<sup>Created on 2023-09-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

These are now available publicly on our demo server, and I did not have to change the access through the UI:

- https://colorado.posit.co/rsc/content/d91d9ec4-c1e9-437a-9393-e55a06b2557d
- https://colorado.posit.co/rsc/content/14f9595f-3bc1-467b-9610-37f5f4ea2b74

The options here for `access_type` are one of `c("acl", "logged_in", "all")`, and you can read more [in the docs](https://pins.rstudio.com/reference/board_connect.html#public-pins).

**Comment by juliasilge** [comment]
Let us know if you have further questions! 🙌
