### ISSUE TITLE
Use of `Tagging` argument in `pin_write` and `pin_upload` sets object tags (AWS S3), but `pin_meta` returns the `tags` entry as NULL

### ISSUE THREAD

**Issue by michaelhogersnplm** [rstudio/pins-r#804]
Hi there, 

Thank you for this package, it is very useful and I noticed something that could possibly be a bug in the pins/paws interaction.

Following the example from https://pins.rstudio.com/reference/board_s3.html, the use of `Tagging` results in objects being correctly tagged in AWS S3, however when using `pins::pin_meta` the `tags` entry is `NULL`.

This only happens when using the `Tagging` argument (for both `pin_write` and `pin_upload`), when using the `tags` argument for `pin_write` (which is not available for `pin_upload`) it is possible to correctly retrieve the tags metadata using `pins::pin_meta`.
 
It does not seem related to permissions, as using `paws::s3` and then `s3::get_object_tagging` allows to retrieve the tag set via the `Tagging` argument.

I am referring to the following example:
```
if (FALSE) {
board <- board_s3("pins-test-hadley", region = "us-east-2")
board %>% pin_write(mtcars)
board %>% pin_read("mtcars")

# A prefix allows you to have multiple independent boards in the same pin.
board_sales <- board_s3("company-pins", prefix = "sales/")
board_marketing <- board_s3("company-pins", prefix = "marketing/")
# You can make the hierarchy arbitrarily deep.

# Pass arguments like `Tagging` through the dots of `pin_write`:
board %>% pin_write(mtcars, Tagging = "key1=value1&key2=value2")

}
```

(pins version 1.2.2)

Best,
Michael

**Comment by juliasilge** [comment]
Ah yep, I can see how that would be confusing in this situation. They _are_ separate and different tag-like entities. 

- The `tags` argument is a pins-specific thing that can be used across all backends, and it can only take a character vector like `c("value1", "value2")`.
- If you use `Tagging` for an S3 board, that gets passed through the dots of `pin_write()` to S3. This only works for S3 and it needs to be like `"key1=value1&key2=value2"`.

If you want to have your `Tagging` values also show up as pins tags, you would need to do something like this:

```r
board %>% pin_write(mtcars, Tagging = "key1=value1&key2=value2", tags = c("value1", "value2"))
```

It's a bit unfortunate that the names (S3-specific and pins-specific) of these are so similar. 😕 Maybe we can improve the documentation to be less confusing.

**Comment by michaelhogersnplm** [comment]
Hi @juliasilge thank you for the quick response! I think for `pin_write` the tagging logic works as expected (in that case I was only using the `tags` argument which would result in `pin::pin_meta` working as expected and the S3 tags looking correct), but when using `pin::pin_upload` I can only use the `Tagging` argument, `tags` is not available it seems. I just happen to be writing some test logic around the object tags for both methods

**Comment by juliasilge** [comment]
Ah yep, great point! I outlined what we need to check in #805; take a look if you like and share any other thoughts. 👍
