### ISSUE TITLE
Error: C stack usage xxx is too close to the limit, with certain input to pin_write metadata parameter

### ISSUE THREAD

**Issue by marioem** [rstudio/pins-r#824]
The following code causes Error: C stack usage  xxx is too close to the limit:

```
    mbm %>% pin_write(wfset_fits1, 
                      name = wfset_s1_name, 
                      description = glue::glue("{prod_name} meanlog prediction workflowsets {transf_msg} {this_rev}"),
                      metadata = list(dataset_name = DS1_df_name,
                                      dataset_version = DS1vers$version[nrow(DS1vers)],
                                      comment = fit_pin_comment,
                                      tuning_metric = opt_metric,
                                      tidymodels_version = packageVersion("tidymodels"),
                                      R_version = R.version['version.string'][[1]]),
                      versioned = T)

Guessing `type = 'rds'`Creating new version '20240412T095624Z-d6b98'Error: C stack usage  15909096 is too close to the limit
```

As a result no data is written to the pin, only the enclosing folder is created.

`mbm` is a board_folder board, located on local disk.

The problem is triggered by `tidymodels_version = packageVersion("tidymodels")`.  I've narrowed down the issue to `write_meta` function (it may be in write_yaml or below).

Workaround consists in casting `packageVersion` result to character.

I'd suggest adding some input sanity checks before writing yaml, or casting to character user-provided input, as default.

BTW, incredibly useful package, using it all the time in my modeling workflows.

BRs,

Mariusz

**Comment by juliasilge** [comment]
Thanks for the report @marioem!

Here is a smaller example that shows the problem:

```r
pins:::to_utf8(list(version = packageVersion("pins")))
```

The problem is that [`to_utf8()` is recursing forever](https://github.com/rstudio/pins-r/blob/b8827ac2d61cda526d01a9a4db57af4d4108bceb/R/utils.R#L79) for this thing:

``` r
class(packageVersion("pins"))
#> [1] "package_version" "numeric_version"
```

<sup>Created on 2024-04-15 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by juliasilge** [comment]
Well, that's _interesting_:

``` r
is.list(packageVersion("pins"))
#> [1] TRUE
str(packageVersion("pins"))
#> Classes 'package_version', 'numeric_version'  hidden list of 1
#>  $ : int [1:3] 1 3 0
```

<sup>Created on 2024-04-15 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

I think your workaround (coercing this funny object to character) is definitely the way to go for now @marioem. We do have lots of sanity checks and coercion, etc, before writing to YAML, but this particular thing is pretty weird:

``` r
x <- packageVersion("pins")
class(x)
#> [1] "package_version" "numeric_version"
class(x[[1]])
#> [1] "package_version" "numeric_version"
class(x[[1]][[1]])
#> [1] "package_version" "numeric_version"
```

<sup>Created on 2024-04-15 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

It just keeps going like that!

**Comment by juliasilge** [comment]
I think the best option for folks in this situation is to coerce ✨ strange ✨ objects such as `packageVersion()` to something that can be written in YAML, like so:

``` r
as.character(packageVersion("pins"))
#> [1] "1.4.0"
```

<sup>Created on 2024-12-13 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
