### ISSUE TITLE
build a package based on pins

### ISSUE THREAD

**Issue by yayayaoyaoyao** [rstudio/pins-r#828]
Thanks for this nice package. I am trying to build a package based on pins. I set up a pins-board on github within the R folder of a newly created package.
When I build up a function, I directly call the pins::board_url, but this cannot pass the CRAN check with the error: object of pins::board_url not found. When I run this function, it works on my computer though. Do you know why? What is the correct procedure to use this in a package?

**Comment by juliasilge** [comment]
That sounds like a problem with how you are managing the package dependencies. Check out:

- The sections on package dependencies in _R Packages_: https://r-pkgs.org/dependencies-mindset-background.html
- The modeldatatoo package, as an example of a package that uses pins: https://github.com/tidymodels/modeldatatoo

If you have your package on GitHub, I would be happy to take a little look!
