### ISSUE TITLE
`pin_upload` doesn't allow 'name' to be fully specified with username prefix

### ISSUE THREAD

**Issue by tommarshall2** [rstudio/pins-r#847]
If there are two content items on a Connect board with the same name, the 'name' of the pin to upload to must be qualified by the username. However, `pin_upload` uses the `pins:::check_pin_name` function, which doesn't allow for slashes in the name.

## Example

I am working with a shared Posit Connect environment, where there are two pins:
1. 'example-user-1/the_pin_name'
2. 'example-user-2/the_pin_name'

Attempting:
```r
library(pins)
board <- board_connect()
pin_upload(board, "data/a_data_file.fst", name = "the_pin_name")
```
Results in:
```
Error in `rsc_content_find()`:
! Multiple pins with name "the_pin_name"
ℹ Use a fully specified name including user name like "julia/the_pin_name"
```

But trying:
```r
library(pins)
board <- board_connect()
pin_upload(board, "data/a_data_file.fst", name = "example-user-1/the_pin_name")
```
Results in:
```
Error in `check_pin_name()`:
! `name` must not contain slashes
```

**Comment by juliasilge** [comment]
We [use `check_pin_name()` in all the board-specific `pin_store` methods](https://github.com/search?q=repo%3Arstudio%2Fpins-r%20check_pin_name&type=code), but then we also have it here in `pin_upload()`:

https://github.com/rstudio/pins-r/blob/621368ce4085f2f7047f080dfdf7b40efdebebf0/R/pin-upload-download.R#L61

It would make more sense for us to treat the relationship between `pin_upload()` and `pin_check_name()` as the relationship between `pin_write()` and `pin_check_name()`, i.e. it is called from the `pin_store` method and not directly in the function.

**Comment by juliasilge** [comment]
Hello there @tommarshall2! 👋 Would you like to try out a possible solution I have set up in #852? You can install with `devtools::install_github("rstudio/pins-r@do-not-check-pin-name-in-pin-upload")`.
