### ISSUE TITLE
save pin to digital ocean

### ISSUE THREAD

**Issue by Sade154** [rstudio/pins-r#851]
Hello,
I saw that the DigitalOcean board is deprecated.
Is there a board_do planed for digital ocean pins ? 
Thanks in advance.

**Comment by juliasilge** [comment]
Thanks for this feature request! We can track interest in a board for Digital Ocean here in this issue.

**Comment by Sade154** [comment]
I just tested it with `board_s3 `and it worked perfectly!

We struggled initially, but with the following parameters, it works exactly as it does with AWS:
```
br <- board_s3(
  bucket = "mybucket",
  access_key = "xxx",
  secret_access_key = "xxxx",
  endpoint = "https://ams3.digitaloceanspaces.com"
)

```
It might be beneficial to include this configuration in the documentation, or perhaps introduce an alias like `board_do `to make users aware that this functionality is supported.

**Comment by juliasilge** [comment]
We did add a bit of documentation for MinIO (another S3 compatible storage backend) here:
https://pins.rstudio.com/reference/board_s3.html#arg-endpoint

Maybe we should add more documentation about S3-compatible but non-AWS backends in general, with a few examples.

**Comment by Sade154** [comment]
That would be great :)
